<?php

namespace App\DataProviders;

abstract class DistrictTehsilDataProvider
{
    // public static function States()
    // {
    //     // state id inline with https://github.com/dipeshsukhia/laravel-country-state-city-data
    //     return [
    //         ['id' => '2723', 'country_id' => '166', 'state' => 'Balochistan'],
    //         ['id' => '2724', 'country_id' => '166', 'state' => 'Federal Capital'],
    //         ['id' => '2725', 'country_id' => '166', 'state' => 'Azad Jammu and Kashmir'],
    //         ['id' => '2726', 'country_id' => '166', 'state' => 'Gilgit-Baltistan'],
    //         ['id' => '2727', 'country_id' => '166', 'state' => 'Khyber Pakhtunkhwa'],
    //         ['id' => '2728', 'country_id' => '166', 'state' => 'Punjab'],
    //         ['id' => '2729', 'country_id' => '166', 'state' => 'Sindh'],
    //     ];
    // }

    public static function Districts()
    {
        return [
            ['id' => '1', 'state_id' => '2723', 'district' => 'Awaran'],
            ['id' => '2', 'state_id' => '2723', 'district' => 'Barkhan'],
            ['id' => '3', 'state_id' => '2723', 'district' => 'Chagai'],
            ['id' => '4', 'state_id' => '2723', 'district' => 'Dera Bugti'],
            ['id' => '5', 'state_id' => '2723', 'district' => 'Duki'],
            ['id' => '6', 'state_id' => '2723', 'district' => 'Gwadar'],
            ['id' => '7', 'state_id' => '2723', 'district' => 'Harnai'],
            ['id' => '8', 'state_id' => '2723', 'district' => 'Jafarabad'],
            ['id' => '9', 'state_id' => '2723', 'district' => 'Jhal Magsi'],
            ['id' => '10', 'state_id' => '2723', 'district' => 'Kachhi'],
            ['id' => '11', 'state_id' => '2723', 'district' => 'Kalat'],
            ['id' => '12', 'state_id' => '2723', 'district' => 'Kech'],
            ['id' => '13', 'state_id' => '2723', 'district' => 'Kharan'],
            ['id' => '14', 'state_id' => '2723', 'district' => 'Khuzdar'],
            ['id' => '15', 'state_id' => '2723', 'district' => 'Killa Abdullah'],
            ['id' => '16', 'state_id' => '2723', 'district' => 'Killa Saifullah'],
            ['id' => '17', 'state_id' => '2723', 'district' => 'Kohlu'],
            ['id' => '18', 'state_id' => '2723', 'district' => 'Lasbela'],
            ['id' => '19', 'state_id' => '2723', 'district' => 'Lehri'],
            ['id' => '20', 'state_id' => '2723', 'district' => 'Loralai'],
            ['id' => '21', 'state_id' => '2723', 'district' => 'Mastung'],
            ['id' => '22', 'state_id' => '2723', 'district' => 'Musakhel'],
            ['id' => '23', 'state_id' => '2723', 'district' => 'Nasirabad'],
            ['id' => '24', 'state_id' => '2723', 'district' => 'Nushki'],
            ['id' => '25', 'state_id' => '2723', 'district' => 'Panjgur'],
            ['id' => '26', 'state_id' => '2723', 'district' => 'Pishin'],
            ['id' => '27', 'state_id' => '2723', 'district' => 'Quetta'],
            ['id' => '28', 'state_id' => '2723', 'district' => 'Sherani'],
            ['id' => '29', 'state_id' => '2723', 'district' => 'Sibi'],
            ['id' => '30', 'state_id' => '2723', 'district' => 'Sohbatpur'],
            ['id' => '31', 'state_id' => '2723', 'district' => 'Washuk'],
            ['id' => '32', 'state_id' => '2723', 'district' => 'Zhob'],
            ['id' => '33', 'state_id' => '2723', 'district' => 'Ziarat'],
            ['id' => '34', 'state_id' => '2724', 'district' => 'Islamabad'],
            ['id' => '35', 'state_id' => '2725', 'district' => 'Muzaffarabad'],
            ['id' => '36', 'state_id' => '2725', 'district' => 'Hattian Bala'],
            ['id' => '37', 'state_id' => '2725', 'district' => 'Neelum'],
            ['id' => '38', 'state_id' => '2725', 'district' => 'Mirpur'],
            ['id' => '39', 'state_id' => '2725', 'district' => 'Bhimber'],
            ['id' => '40', 'state_id' => '2725', 'district' => 'Kotli'],
            ['id' => '41', 'state_id' => '2725', 'district' => 'Poonch'],
            ['id' => '42', 'state_id' => '2725', 'district' => 'Bagh'],
            ['id' => '43', 'state_id' => '2725', 'district' => 'Haveli'],
            ['id' => '44', 'state_id' => '2725', 'district' => 'Sudhnati'],
            ['id' => '45', 'state_id' => '2726', 'district' => 'Ghanche'],
            ['id' => '46', 'state_id' => '2726', 'district' => 'Skardu'],
            ['id' => '47', 'state_id' => '2726', 'district' => 'Astore'],
            ['id' => '48', 'state_id' => '2726', 'district' => 'Diamer'],
            ['id' => '49', 'state_id' => '2726', 'district' => 'Ghizer'],
            ['id' => '50', 'state_id' => '2726', 'district' => 'Gilgit'],
            ['id' => '51', 'state_id' => '2726', 'district' => 'Hunza'],
            ['id' => '52', 'state_id' => '2726', 'district' => 'Kharmang'],
            ['id' => '53', 'state_id' => '2726', 'district' => 'Shigar'],
            ['id' => '54', 'state_id' => '2726', 'district' => 'Nagar'],
            ['id' => '55', 'state_id' => '2726', 'district' => 'Gupis–Yasin'],
            ['id' => '56', 'state_id' => '2726', 'district' => 'Tangir'],
            ['id' => '57', 'state_id' => '2726', 'district' => 'Darel'],
            ['id' => '58', 'state_id' => '2726', 'district' => 'Roundu'],
            ['id' => '59', 'state_id' => '2727', 'district' => 'Abbottabad'],
            ['id' => '60', 'state_id' => '2727', 'district' => 'Bajaur'],
            ['id' => '61', 'state_id' => '2727', 'district' => 'Bannu'],
            ['id' => '62', 'state_id' => '2727', 'district' => 'Battagram'],
            ['id' => '63', 'state_id' => '2727', 'district' => 'Buner'],
            ['id' => '64', 'state_id' => '2727', 'district' => 'Charsadda'],
            ['id' => '65', 'state_id' => '2727', 'district' => 'Chitral'],
            ['id' => '66', 'state_id' => '2727', 'district' => 'Dera Ismail Khan'],
            ['id' => '67', 'state_id' => '2727', 'district' => 'Hangu'],
            ['id' => '68', 'state_id' => '2727', 'district' => 'Haripur'],
            ['id' => '69', 'state_id' => '2727', 'district' => 'Karak'],
            ['id' => '70', 'state_id' => '2727', 'district' => 'Khyber'],
            ['id' => '71', 'state_id' => '2727', 'district' => 'Kohat'],
            ['id' => '72', 'state_id' => '2727', 'district' => 'Kurram'],
            ['id' => '73', 'state_id' => '2727', 'district' => 'Lakki Marwat'],
            ['id' => '74', 'state_id' => '2727', 'district' => 'Lower Dir'],
            ['id' => '75', 'state_id' => '2727', 'district' => 'Lower Kohistan'],
            ['id' => '76', 'state_id' => '2727', 'district' => 'Malakand'],
            ['id' => '77', 'state_id' => '2727', 'district' => 'Mansehra'],
            ['id' => '78', 'state_id' => '2727', 'district' => 'Mardan'],
            ['id' => '79', 'state_id' => '2727', 'district' => 'Mohmand'],
            ['id' => '80', 'state_id' => '2727', 'district' => 'North Waziristan'],
            ['id' => '81', 'state_id' => '2727', 'district' => 'Nowshera'],
            ['id' => '82', 'state_id' => '2727', 'district' => 'Orakzai'],
            ['id' => '83', 'state_id' => '2727', 'district' => 'Peshawar'],
            ['id' => '84', 'state_id' => '2727', 'district' => 'Shangla'],
            ['id' => '85', 'state_id' => '2727', 'district' => 'South Waziristan'],
            ['id' => '86', 'state_id' => '2727', 'district' => 'Swabi'],
            ['id' => '87', 'state_id' => '2727', 'district' => 'Swat'],
            ['id' => '88', 'state_id' => '2727', 'district' => 'Tank'],
            ['id' => '89', 'state_id' => '2727', 'district' => 'Torghar'],
            ['id' => '90', 'state_id' => '2727', 'district' => 'Upper Dir'],
            ['id' => '91', 'state_id' => '2727', 'district' => 'Upper Kohistan'],
            ['id' => '92', 'state_id' => '2728', 'district' => 'Attock'],
            ['id' => '93', 'state_id' => '2728', 'district' => 'Bahawalnagar'],
            ['id' => '94', 'state_id' => '2728', 'district' => 'Bahawalpur'],
            ['id' => '95', 'state_id' => '2728', 'district' => 'Bhakkar'],
            ['id' => '96', 'state_id' => '2728', 'district' => 'Chakwal'],
            ['id' => '97', 'state_id' => '2728', 'district' => 'Chiniot'],
            ['id' => '98', 'state_id' => '2728', 'district' => 'Dera Ghazi Khan'],
            ['id' => '99', 'state_id' => '2728', 'district' => 'Faisalabad'],
            ['id' => '100', 'state_id' => '2728', 'district' => 'Gujranwala'],
            ['id' => '101', 'state_id' => '2728', 'district' => 'Gujrat'],
            ['id' => '102', 'state_id' => '2728', 'district' => 'Hafizabad'],
            ['id' => '103', 'state_id' => '2728', 'district' => 'Jhang'],
            ['id' => '104', 'state_id' => '2728', 'district' => 'Jhelum'],
            ['id' => '105', 'state_id' => '2728', 'district' => 'Kasur'],
            ['id' => '106', 'state_id' => '2728', 'district' => 'Khanewal'],
            ['id' => '107', 'state_id' => '2728', 'district' => 'Khushab'],
            ['id' => '108', 'state_id' => '2728', 'district' => 'Lahore'],
            ['id' => '109', 'state_id' => '2728', 'district' => 'Layyah'],
            ['id' => '110', 'state_id' => '2728', 'district' => 'Lodhran'],
            ['id' => '111', 'state_id' => '2728', 'district' => 'Mandi Bahauddin'],
            ['id' => '112', 'state_id' => '2728', 'district' => 'Mianwali'],
            ['id' => '113', 'state_id' => '2728', 'district' => 'Multan'],
            ['id' => '114', 'state_id' => '2728', 'district' => 'Muzaffargarh'],
            ['id' => '115', 'state_id' => '2728', 'district' => 'Narowal'],
            ['id' => '116', 'state_id' => '2728', 'district' => 'Nankana Sahib'],
            ['id' => '117', 'state_id' => '2728', 'district' => 'Okara'],
            ['id' => '118', 'state_id' => '2728', 'district' => 'Pakpattan'],
            ['id' => '119', 'state_id' => '2728', 'district' => 'Rahim Yar Khan'],
            ['id' => '120', 'state_id' => '2728', 'district' => 'Rajanpur'],
            ['id' => '121', 'state_id' => '2728', 'district' => 'Rawalpindi'],
            ['id' => '122', 'state_id' => '2728', 'district' => 'Sahiwal'],
            ['id' => '123', 'state_id' => '2728', 'district' => 'Sargodha'],
            ['id' => '124', 'state_id' => '2728', 'district' => 'Sheikhupura'],
            ['id' => '125', 'state_id' => '2728', 'district' => 'Sialkot'],
            ['id' => '126', 'state_id' => '2728', 'district' => 'Toba Tek Singh'],
            ['id' => '127', 'state_id' => '2728', 'district' => 'Vehari'],
            ['id' => '128', 'state_id' => '2729', 'district' => 'Badin'],
            ['id' => '129', 'state_id' => '2729', 'district' => 'Dadu'],
            ['id' => '130', 'state_id' => '2729', 'district' => 'Ghotki'],
            ['id' => '131', 'state_id' => '2729', 'district' => 'Hyderabad'],
            ['id' => '132', 'state_id' => '2729', 'district' => 'Jacobabad'],
            ['id' => '133', 'state_id' => '2729', 'district' => 'Jamshoro'],
            ['id' => '134', 'state_id' => '2729', 'district' => 'Karachi Central'],
            ['id' => '135', 'state_id' => '2729', 'district' => 'Karachi East'],
            ['id' => '136', 'state_id' => '2729', 'district' => 'Karachi South'],
            ['id' => '137', 'state_id' => '2729', 'district' => 'Karachi West'],
            ['id' => '138', 'state_id' => '2729', 'district' => 'Kashmore'],
            ['id' => '139', 'state_id' => '2729', 'district' => 'Khairpur'],
            ['id' => '140', 'state_id' => '2729', 'district' => 'Korangi'],
            ['id' => '141', 'state_id' => '2729', 'district' => 'Larkana'],
            ['id' => '142', 'state_id' => '2729', 'district' => 'Malir'],
            ['id' => '143', 'state_id' => '2729', 'district' => 'Matiari'],
            ['id' => '144', 'state_id' => '2729', 'district' => 'Mirpur Khas'],
            ['id' => '145', 'state_id' => '2729', 'district' => 'Naushahro Feroze'],
            ['id' => '146', 'state_id' => '2729', 'district' => 'Qambar Shahdadkot'],
            ['id' => '147', 'state_id' => '2729', 'district' => 'Sanghar'],
            ['id' => '148', 'state_id' => '2729', 'district' => 'Shaheed Benazir Abad'],
            ['id' => '149', 'state_id' => '2729', 'district' => 'Shikarpur'],
            ['id' => '150', 'state_id' => '2729', 'district' => 'Sujawal'],
            ['id' => '151', 'state_id' => '2729', 'district' => 'Sukkur'],
            ['id' => '152', 'state_id' => '2729', 'district' => 'Tando Allahyar'],
            ['id' => '153', 'state_id' => '2729', 'district' => 'Tando Muhammad Khan'],
            ['id' => '154', 'state_id' => '2729', 'district' => 'Tharparkar'],
            ['id' => '155', 'state_id' => '2729', 'district' => 'Thatta'],
            ['id' => '156', 'state_id' => '2729', 'district' => 'Umerkot'],
        ];
    }

    public static function Tehsils()
    {
        return [
            ['id' => '1', 'district_id' => '1', 'tehsil' => 'Awaran'],
            ['id' => '2', 'district_id' => '1', 'tehsil' => 'Gishkore'],
            ['id' => '3', 'district_id' => '1', 'tehsil' => 'Jhal Jhao'],
            ['id' => '4', 'district_id' => '1', 'tehsil' => 'Korak Jahoo'],
            ['id' => '5', 'district_id' => '1', 'tehsil' => 'Mashkai'],
            ['id' => '6', 'district_id' => '2', 'tehsil' => 'Barkhan'],
            ['id' => '7', 'district_id' => '3', 'tehsil' => 'Dalbandin'],
            ['id' => '8', 'district_id' => '3', 'tehsil' => 'Nokundi'],
            ['id' => '9', 'district_id' => '3', 'tehsil' => 'Taftan'],
            ['id' => '10', 'district_id' => '3', 'tehsil' => 'Chagai'],
            ['id' => '11', 'district_id' => '4', 'tehsil' => 'Dera Bugti'],
            ['id' => '12', 'district_id' => '4', 'tehsil' => 'Phelawagh'],
            ['id' => '13', 'district_id' => '4', 'tehsil' => 'Sui'],
            ['id' => '14', 'district_id' => '4', 'tehsil' => 'Baiker'],
            ['id' => '15', 'district_id' => '4', 'tehsil' => 'Loti'],
            ['id' => '16', 'district_id' => '4', 'tehsil' => 'Malam'],
            ['id' => '17', 'district_id' => '4', 'tehsil' => 'Pir Koh'],
            ['id' => '18', 'district_id' => '4', 'tehsil' => 'Sangsillah'],
            ['id' => '19', 'district_id' => '5', 'tehsil' => 'Duki'],
            ['id' => '20', 'district_id' => '6', 'tehsil' => 'Gwadar'],
            ['id' => '21', 'district_id' => '6', 'tehsil' => 'Jiwani'],
            ['id' => '22', 'district_id' => '6', 'tehsil' => 'Ormara'],
            ['id' => '23', 'district_id' => '6', 'tehsil' => 'Pasni'],
            ['id' => '24', 'district_id' => '6', 'tehsil' => 'Suntsar'],
            ['id' => '25', 'district_id' => '7', 'tehsil' => 'Harnai'],
            ['id' => '26', 'district_id' => '7', 'tehsil' => 'Sharigh'],
            ['id' => '27', 'district_id' => '7', 'tehsil' => 'Khoast'],
            ['id' => '28', 'district_id' => '8', 'tehsil' => 'Gandakha'],
            ['id' => '29', 'district_id' => '8', 'tehsil' => 'Jhat Pat'],
            ['id' => '30', 'district_id' => '8', 'tehsil' => 'Usta Mohammad'],
            ['id' => '31', 'district_id' => '9', 'tehsil' => 'Gandawa'],
            ['id' => '32', 'district_id' => '9', 'tehsil' => 'Jhal Magsi'],
            ['id' => '33', 'district_id' => '9', 'tehsil' => 'Mirpur'],
            ['id' => '34', 'district_id' => '10', 'tehsil' => 'Dhadar'],
            ['id' => '35', 'district_id' => '10', 'tehsil' => 'Balanari'],
            ['id' => '36', 'district_id' => '10', 'tehsil' => 'Khattan'],
            ['id' => '37', 'district_id' => '10', 'tehsil' => 'Mach'],
            ['id' => '38', 'district_id' => '10', 'tehsil' => 'Sanni'],
            ['id' => '39', 'district_id' => '11', 'tehsil' => 'Kalat'],
            ['id' => '40', 'district_id' => '11', 'tehsil' => 'Mangochar'],
            ['id' => '41', 'district_id' => '11', 'tehsil' => 'Surab'],
            ['id' => '42', 'district_id' => '11', 'tehsil' => 'Gazg'],
            ['id' => '43', 'district_id' => '11', 'tehsil' => 'Johan'],
            ['id' => '44', 'district_id' => '12', 'tehsil' => 'Mand'],
            ['id' => '45', 'district_id' => '12', 'tehsil' => 'Tump'],
            ['id' => '46', 'district_id' => '12', 'tehsil' => 'Turbat'],
            ['id' => '47', 'district_id' => '12', 'tehsil' => 'Balnigwar'],
            ['id' => '48', 'district_id' => '12', 'tehsil' => 'Buleda'],
            ['id' => '49', 'district_id' => '12', 'tehsil' => 'Dasht'],
            ['id' => '50', 'district_id' => '12', 'tehsil' => 'Hoshab'],
            ['id' => '51', 'district_id' => '12', 'tehsil' => 'Zamuran'],
            ['id' => '52', 'district_id' => '12', 'tehsil' => 'Dandaar'],
            ['id' => '53', 'district_id' => '13', 'tehsil' => 'Kharan'],
            ['id' => '54', 'district_id' => '13', 'tehsil' => 'Sar-Kharan'],
            ['id' => '55', 'district_id' => '13', 'tehsil' => 'Tohumulk'],
            ['id' => '56', 'district_id' => '14', 'tehsil' => 'Khuzdar'],
            ['id' => '57', 'district_id' => '14', 'tehsil' => 'Nall'],
            ['id' => '58', 'district_id' => '14', 'tehsil' => 'Wadh'],
            ['id' => '59', 'district_id' => '14', 'tehsil' => 'Zehri'],
            ['id' => '60', 'district_id' => '14', 'tehsil' => 'Baghbana'],
            ['id' => '61', 'district_id' => '14', 'tehsil' => 'Aranji'],
            ['id' => '62', 'district_id' => '14', 'tehsil' => 'Greshek'],
            ['id' => '63', 'district_id' => '14', 'tehsil' => 'Karakh'],
            ['id' => '64', 'district_id' => '14', 'tehsil' => 'Moola'],
            ['id' => '65', 'district_id' => '14', 'tehsil' => 'Ornach'],
            ['id' => '66', 'district_id' => '14', 'tehsil' => 'Saroona'],
            ['id' => '67', 'district_id' => '15', 'tehsil' => 'Chaman'],
            ['id' => '68', 'district_id' => '15', 'tehsil' => 'Gulistan'],
            ['id' => '69', 'district_id' => '15', 'tehsil' => 'Killa Abdullah'],
            ['id' => '70', 'district_id' => '15', 'tehsil' => 'Dobani'],
            ['id' => '71', 'district_id' => '16', 'tehsil' => 'Killa Saifullah'],
            ['id' => '72', 'district_id' => '16', 'tehsil' => 'Loiband'],
            ['id' => '73', 'district_id' => '16', 'tehsil' => 'Muslim Bagh'],
            ['id' => '74', 'district_id' => '16', 'tehsil' => 'Badini'],
            ['id' => '75', 'district_id' => '16', 'tehsil' => 'Kanmetharzai'],
            ['id' => '76', 'district_id' => '16', 'tehsil' => 'Shinki'],
            ['id' => '77', 'district_id' => '17', 'tehsil' => 'Kahan'],
            ['id' => '78', 'district_id' => '17', 'tehsil' => 'Kohlu'],
            ['id' => '79', 'district_id' => '17', 'tehsil' => 'Maiwand'],
            ['id' => '80', 'district_id' => '17', 'tehsil' => 'Tamboo'],
            ['id' => '81', 'district_id' => '17', 'tehsil' => 'Grisini'],
            ['id' => '82', 'district_id' => '18', 'tehsil' => 'Bela'],
            ['id' => '83', 'district_id' => '18', 'tehsil' => 'Dureji'],
            ['id' => '84', 'district_id' => '18', 'tehsil' => 'Gaddani'],
            ['id' => '85', 'district_id' => '18', 'tehsil' => 'Hub'],
            ['id' => '86', 'district_id' => '18', 'tehsil' => 'Kanraj'],
            ['id' => '87', 'district_id' => '18', 'tehsil' => 'Lakhra'],
            ['id' => '88', 'district_id' => '18', 'tehsil' => 'Sonmiani (Winder)'],
            ['id' => '89', 'district_id' => '18', 'tehsil' => 'Uthal'],
            ['id' => '90', 'district_id' => '18', 'tehsil' => 'Liari'],
            ['id' => '91', 'district_id' => '19', 'tehsil' => 'Bhag'],
            ['id' => '92', 'district_id' => '19', 'tehsil' => 'Lehri'],
            ['id' => '93', 'district_id' => '20', 'tehsil' => 'Bori'],
            ['id' => '94', 'district_id' => '20', 'tehsil' => 'Duki'],
            ['id' => '95', 'district_id' => '20', 'tehsil' => 'Loralai'],
            ['id' => '96', 'district_id' => '20', 'tehsil' => 'Mekhtar'],
            ['id' => '97', 'district_id' => '21', 'tehsil' => 'Dasht'],
            ['id' => '98', 'district_id' => '21', 'tehsil' => 'Mastung'],
            ['id' => '99', 'district_id' => '21', 'tehsil' => 'Khad Koocha'],
            ['id' => '100', 'district_id' => '21', 'tehsil' => 'Kirdgap'],
            ['id' => '101', 'district_id' => '22', 'tehsil' => 'Drug'],
            ['id' => '102', 'district_id' => '22', 'tehsil' => 'Kingri'],
            ['id' => '103', 'district_id' => '22', 'tehsil' => 'Musakhel'],
            ['id' => '104', 'district_id' => '22', 'tehsil' => 'Toisar'],
            ['id' => '105', 'district_id' => '23', 'tehsil' => 'Baba Kot'],
            ['id' => '106', 'district_id' => '23', 'tehsil' => 'Dera Murad Jamali'],
            ['id' => '107', 'district_id' => '23', 'tehsil' => 'Tamboo'],
            ['id' => '108', 'district_id' => '23', 'tehsil' => 'Chattar'],
            ['id' => '109', 'district_id' => '24', 'tehsil' => 'Nushki'],
            ['id' => '110', 'district_id' => '24', 'tehsil' => 'Dak'],
            ['id' => '111', 'district_id' => '25', 'tehsil' => 'Gowargo'],
            ['id' => '112', 'district_id' => '25', 'tehsil' => 'Panjgur'],
            ['id' => '113', 'district_id' => '25', 'tehsil' => 'Paroom'],
            ['id' => '114', 'district_id' => '25', 'tehsil' => 'Gichk'],
            ['id' => '115', 'district_id' => '26', 'tehsil' => 'Hurramzai'],
            ['id' => '116', 'district_id' => '26', 'tehsil' => 'Karezat'],
            ['id' => '117', 'district_id' => '26', 'tehsil' => 'Pishin'],
            ['id' => '118', 'district_id' => '26', 'tehsil' => 'Saranan'],
            ['id' => '119', 'district_id' => '26', 'tehsil' => 'Barshore'],
            ['id' => '120', 'district_id' => '27', 'tehsil' => 'Chiltan'],
            ['id' => '121', 'district_id' => '27', 'tehsil' => 'Zarghoon'],
            ['id' => '122', 'district_id' => '27', 'tehsil' => 'Panjpai'],
            ['id' => '123', 'district_id' => '28', 'tehsil' => 'Sherani'],
            ['id' => '124', 'district_id' => '29', 'tehsil' => 'Sibi'],
            ['id' => '125', 'district_id' => '29', 'tehsil' => 'Kutmandai'],
            ['id' => '126', 'district_id' => '29', 'tehsil' => 'Sangan'],
            ['id' => '127', 'district_id' => '30', 'tehsil' => 'Faridabad'],
            ['id' => '128', 'district_id' => '30', 'tehsil' => 'Hairdeen'],
            ['id' => '129', 'district_id' => '30', 'tehsil' => 'Manjipur'],
            ['id' => '130', 'district_id' => '30', 'tehsil' => 'Sohbatpur'],
            ['id' => '131', 'district_id' => '31', 'tehsil' => 'Besima'],
            ['id' => '132', 'district_id' => '31', 'tehsil' => 'Mashkhel'],
            ['id' => '133', 'district_id' => '31', 'tehsil' => 'Washuk'],
            ['id' => '134', 'district_id' => '31', 'tehsil' => 'Nag'],
            ['id' => '135', 'district_id' => '31', 'tehsil' => 'Shahgori'],
            ['id' => '136', 'district_id' => '32', 'tehsil' => 'Ashwat'],
            ['id' => '137', 'district_id' => '32', 'tehsil' => 'Qamar Din Karez'],
            ['id' => '138', 'district_id' => '32', 'tehsil' => 'Kashatu'],
            ['id' => '139', 'district_id' => '32', 'tehsil' => 'Sambaza'],
            ['id' => '140', 'district_id' => '32', 'tehsil' => 'Zhob'],
            ['id' => '141', 'district_id' => '33', 'tehsil' => 'Ziarat'],
            ['id' => '142', 'district_id' => '33', 'tehsil' => 'Sinjavi'],
            ['id' => '143', 'district_id' => '34', 'tehsil' => 'Islamabad'],
            ['id' => '144', 'district_id' => '35', 'tehsil' => 'Muzaffarabad'],
            ['id' => '145', 'district_id' => '35', 'tehsil' => 'Nasirabad'],
            ['id' => '146', 'district_id' => '36', 'tehsil' => 'Hattian Bala'],
            ['id' => '147', 'district_id' => '36', 'tehsil' => 'Chikkar'],
            ['id' => '148', 'district_id' => '36', 'tehsil' => 'Leepa'],
            ['id' => '149', 'district_id' => '37', 'tehsil' => 'Athmuqam'],
            ['id' => '150', 'district_id' => '37', 'tehsil' => 'Sharda'],
            ['id' => '151', 'district_id' => '38', 'tehsil' => 'Dadyal'],
            ['id' => '152', 'district_id' => '38', 'tehsil' => 'Mirpur'],
            ['id' => '153', 'district_id' => '39', 'tehsil' => 'Bhimber'],
            ['id' => '154', 'district_id' => '39', 'tehsil' => 'Barnala'],
            ['id' => '155', 'district_id' => '39', 'tehsil' => 'Samahni'],
            ['id' => '156', 'district_id' => '40', 'tehsil' => 'Kotli'],
            ['id' => '157', 'district_id' => '40', 'tehsil' => 'Khuiratta'],
            ['id' => '158', 'district_id' => '40', 'tehsil' => 'Fatehpur Thakiala-Nakyal'],
            ['id' => '159', 'district_id' => '40', 'tehsil' => 'Sehnsa'],
            ['id' => '160', 'district_id' => '40', 'tehsil' => 'Charoi'],
            ['id' => '161', 'district_id' => '41', 'tehsil' => 'Abbaspur'],
            ['id' => '162', 'district_id' => '41', 'tehsil' => 'Hajira'],
            ['id' => '163', 'district_id' => '41', 'tehsil' => 'Rawalakot'],
            ['id' => '164', 'district_id' => '41', 'tehsil' => 'Thorar'],
            ['id' => '165', 'district_id' => '42', 'tehsil' => 'Bagh'],
            ['id' => '166', 'district_id' => '42', 'tehsil' => 'Dhirkot'],
            ['id' => '167', 'district_id' => '42', 'tehsil' => 'Hari Ghel'],
            ['id' => '168', 'district_id' => '43', 'tehsil' => 'Haveli'],
            ['id' => '169', 'district_id' => '43', 'tehsil' => 'Khurshidabad'],
            ['id' => '170', 'district_id' => '43', 'tehsil' => 'Mumtazabad'],
            ['id' => '171', 'district_id' => '44', 'tehsil' => 'Baloch'],
            ['id' => '172', 'district_id' => '44', 'tehsil' => 'Mang'],
            ['id' => '173', 'district_id' => '44', 'tehsil' => 'Pallandri'],
            ['id' => '174', 'district_id' => '44', 'tehsil' => 'Tarar Khel'],
            ['id' => '175', 'district_id' => '45', 'tehsil' => 'Kharko'],
            ['id' => '176', 'district_id' => '45', 'tehsil' => 'Khaplu'],
            ['id' => '177', 'district_id' => '45', 'tehsil' => 'Mashabrum'],
            ['id' => '178', 'district_id' => '46', 'tehsil' => 'Gultari'],
            ['id' => '179', 'district_id' => '46', 'tehsil' => 'Skardu'],
            ['id' => '180', 'district_id' => '47', 'tehsil' => 'Astore'],
            ['id' => '181', 'district_id' => '47', 'tehsil' => 'Shounter'],
            ['id' => '182', 'district_id' => '48', 'tehsil' => 'Babusar'],
            ['id' => '183', 'district_id' => '48', 'tehsil' => 'Chilas Tehsil'],
            ['id' => '184', 'district_id' => '49', 'tehsil' => 'Punial'],
            ['id' => '185', 'district_id' => '49', 'tehsil' => 'Ishkoman'],
            ['id' => '186', 'district_id' => '50', 'tehsil' => 'Danyor'],
            ['id' => '187', 'district_id' => '50', 'tehsil' => 'Gilgit'],
            ['id' => '188', 'district_id' => '50', 'tehsil' => 'Juglot'],
            ['id' => '189', 'district_id' => '51', 'tehsil' => 'Aliabad'],
            ['id' => '190', 'district_id' => '51', 'tehsil' => 'Gojal'],
            ['id' => '191', 'district_id' => '52', 'tehsil' => 'Kharmang'],
            ['id' => '192', 'district_id' => '53', 'tehsil' => 'Shigar'],
            ['id' => '193', 'district_id' => '54', 'tehsil' => 'Nagar-I'],
            ['id' => '194', 'district_id' => '54', 'tehsil' => 'Nagar-II'],
            ['id' => '195', 'district_id' => '55', 'tehsil' => 'Gupis'],
            ['id' => '196', 'district_id' => '55', 'tehsil' => 'Yasin'],
            ['id' => '197', 'district_id' => '55', 'tehsil' => 'Phander'],
            ['id' => '198', 'district_id' => '56', 'tehsil' => 'Tangir'],
            ['id' => '199', 'district_id' => '57', 'tehsil' => 'Darel'],
            ['id' => '200', 'district_id' => '58', 'tehsil' => 'Roundu'],
            ['id' => '201', 'district_id' => '59', 'tehsil' => 'Abbottabad'],
            ['id' => '202', 'district_id' => '59', 'tehsil' => 'Havelian'],
            ['id' => '203', 'district_id' => '59', 'tehsil' => 'Lora'],
            ['id' => '204', 'district_id' => '59', 'tehsil' => 'Lower tanawal'],
            ['id' => '205', 'district_id' => '60', 'tehsil' => 'Bajaur'],
            ['id' => '206', 'district_id' => '61', 'tehsil' => 'Bannu'],
            ['id' => '207', 'district_id' => '61', 'tehsil' => 'Domel'],
            ['id' => '208', 'district_id' => '61', 'tehsil' => 'kaki '],
            ['id' => '209', 'district_id' => '62', 'tehsil' => 'Allai'],
            ['id' => '210', 'district_id' => '62', 'tehsil' => 'Battagram'],
            ['id' => '211', 'district_id' => '63', 'tehsil' => 'Daggar (Buner)'],
            ['id' => '212', 'district_id' => '63', 'tehsil' => 'Gagra'],
            ['id' => '213', 'district_id' => '63', 'tehsil' => 'Khudu Khel'],
            ['id' => '214', 'district_id' => '63', 'tehsil' => 'Mandanr'],
            ['id' => '215', 'district_id' => '63', 'tehsil' => 'Salarzi Tehsil'],
            ['id' => '216', 'district_id' => '64', 'tehsil' => 'Charsadda'],
            ['id' => '217', 'district_id' => '64', 'tehsil' => 'Shabqadar'],
            ['id' => '218', 'district_id' => '64', 'tehsil' => 'Tangi'],
            ['id' => '219', 'district_id' => '65', 'tehsil' => 'Mastuj'],
            ['id' => '220', 'district_id' => '65', 'tehsil' => 'Mulkhow/Torkhow'],
            ['id' => '221', 'district_id' => '65', 'tehsil' => 'Chitral'],
            ['id' => '222', 'district_id' => '65', 'tehsil' => 'Drosh'],
            ['id' => '223', 'district_id' => '66', 'tehsil' => 'Dera Ismail Khan'],
            ['id' => '224', 'district_id' => '66', 'tehsil' => 'Daraban'],
            ['id' => '225', 'district_id' => '66', 'tehsil' => 'Kulachi'],
            ['id' => '226', 'district_id' => '66', 'tehsil' => 'Paharpur'],
            ['id' => '227', 'district_id' => '66', 'tehsil' => 'Paroa'],
            ['id' => '228', 'district_id' => '67', 'tehsil' => 'Hangu'],
            ['id' => '229', 'district_id' => '67', 'tehsil' => 'Tall'],
            ['id' => '230', 'district_id' => '68', 'tehsil' => 'Ghazi'],
            ['id' => '231', 'district_id' => '68', 'tehsil' => 'Haripur'],
            ['id' => '232', 'district_id' => '68', 'tehsil' => 'Khanpur'],
            ['id' => '233', 'district_id' => '69', 'tehsil' => 'Banda Daud Shah'],
            ['id' => '234', 'district_id' => '69', 'tehsil' => 'Karak'],
            ['id' => '235', 'district_id' => '69', 'tehsil' => 'Takht-e-Nasrati'],
            ['id' => '236', 'district_id' => '70', 'tehsil' => 'Khyber'],
            ['id' => '237', 'district_id' => '71', 'tehsil' => 'Kohat'],
            ['id' => '238', 'district_id' => '71', 'tehsil' => 'Lachi'],
            ['id' => '239', 'district_id' => '71', 'tehsil' => 'Kurram'],
            ['id' => '240', 'district_id' => '73', 'tehsil' => 'Lakki Marwat'],
            ['id' => '241', 'district_id' => '73', 'tehsil' => 'Sari Naurang'],
            ['id' => '242', 'district_id' => '74', 'tehsil' => 'Adenzai'],
            ['id' => '243', 'district_id' => '74', 'tehsil' => 'Lal Qilla'],
            ['id' => '244', 'district_id' => '74', 'tehsil' => 'Samarbagh'],
            ['id' => '245', 'district_id' => '74', 'tehsil' => 'Timergara'],
            ['id' => '246', 'district_id' => '74', 'tehsil' => 'Khal'],
            ['id' => '247', 'district_id' => '75', 'tehsil' => 'Bankad'],
            ['id' => '248', 'district_id' => '75', 'tehsil' => 'Pattan'],
            ['id' => '249', 'district_id' => '76', 'tehsil' => 'Sam Rani Zai'],
            ['id' => '250', 'district_id' => '76', 'tehsil' => 'Swat Rani Zai'],
            ['id' => '251', 'district_id' => '77', 'tehsil' => 'Bala Kot'],
            ['id' => '252', 'district_id' => '77', 'tehsil' => 'Mansehra'],
            ['id' => '253', 'district_id' => '77', 'tehsil' => 'Oghi'],
            ['id' => '254', 'district_id' => '77', 'tehsil' => 'Baffa Pakhal'],
            ['id' => '255', 'district_id' => '77', 'tehsil' => 'Darband'],
            ['id' => '256', 'district_id' => '78', 'tehsil' => 'Katlang'],
            ['id' => '257', 'district_id' => '78', 'tehsil' => 'Rustam'],
            ['id' => '258', 'district_id' => '78', 'tehsil' => 'Ghari Kapura'],
            ['id' => '259', 'district_id' => '78', 'tehsil' => 'Mardan'],
            ['id' => '260', 'district_id' => '78', 'tehsil' => 'Takht Bhai'],
            ['id' => '261', 'district_id' => '78', 'tehsil' => 'Lund Khwar'],
            ['id' => '262', 'district_id' => '79', 'tehsil' => 'Mohmand'],
            ['id' => '263', 'district_id' => '80', 'tehsil' => 'North Waziristan'],
            ['id' => '264', 'district_id' => '81', 'tehsil' => 'Jahangira'],
            ['id' => '265', 'district_id' => '81', 'tehsil' => 'Nowshera'],
            ['id' => '266', 'district_id' => '81', 'tehsil' => 'Pabbi'],
            ['id' => '267', 'district_id' => '82', 'tehsil' => 'Orakzai'],
            ['id' => '268', 'district_id' => '83', 'tehsil' => 'Peshawar'],
            ['id' => '269', 'district_id' => '84', 'tehsil' => 'Alpuri'],
            ['id' => '270', 'district_id' => '84', 'tehsil' => 'Bisham'],
            ['id' => '271', 'district_id' => '84', 'tehsil' => 'Puran'],
            ['id' => '272', 'district_id' => '84', 'tehsil' => 'Chakesar'],
            ['id' => '273', 'district_id' => '85', 'tehsil' => 'South Waziristan'],
            ['id' => '274', 'district_id' => '86', 'tehsil' => 'Lahor'],
            ['id' => '275', 'district_id' => '86', 'tehsil' => 'Razar'],
            ['id' => '276', 'district_id' => '86', 'tehsil' => 'Swabi'],
            ['id' => '277', 'district_id' => '86', 'tehsil' => 'Topi'],
            ['id' => '278', 'district_id' => '87', 'tehsil' => 'Babuzai (Swat)'],
            ['id' => '279', 'district_id' => '87', 'tehsil' => 'Barikot'],
            ['id' => '280', 'district_id' => '87', 'tehsil' => 'Behrain'],
            ['id' => '281', 'district_id' => '87', 'tehsil' => 'Charbagh'],
            ['id' => '282', 'district_id' => '87', 'tehsil' => 'Kabal'],
            ['id' => '283', 'district_id' => '87', 'tehsil' => 'Khwaza Khela'],
            ['id' => '284', 'district_id' => '87', 'tehsil' => 'Matta'],
            ['id' => '285', 'district_id' => '88', 'tehsil' => 'Tank'],
            ['id' => '286', 'district_id' => '89', 'tehsil' => 'Judba'],
            ['id' => '287', 'district_id' => '89', 'tehsil' => 'Khander'],
            ['id' => '288', 'district_id' => '90', 'tehsil' => 'Dir'],
            ['id' => '289', 'district_id' => '90', 'tehsil' => 'Sharingal'],
            ['id' => '290', 'district_id' => '90', 'tehsil' => 'Wari'],
            ['id' => '291', 'district_id' => '91', 'tehsil' => 'Dassu'],
            ['id' => '292', 'district_id' => '91', 'tehsil' => 'Kandia'],
            ['id' => '293', 'district_id' => '92', 'tehsil' => 'Attock'],
            ['id' => '294', 'district_id' => '92', 'tehsil' => 'Fateh Jang'],
            ['id' => '295', 'district_id' => '92', 'tehsil' => 'HasanAbdal'],
            ['id' => '296', 'district_id' => '92', 'tehsil' => 'Hazro'],
            ['id' => '297', 'district_id' => '92', 'tehsil' => 'Jand'],
            ['id' => '298', 'district_id' => '92', 'tehsil' => 'Pindi Gheb'],
            ['id' => '299', 'district_id' => '93', 'tehsil' => 'Bahawalnagar'],
            ['id' => '300', 'district_id' => '93', 'tehsil' => 'Chishtian'],
            ['id' => '301', 'district_id' => '93', 'tehsil' => 'Haroonabad'],
            ['id' => '302', 'district_id' => '93', 'tehsil' => 'Minchinabad'],
            ['id' => '303', 'district_id' => '94', 'tehsil' => 'Ahmadpur East'],
            ['id' => '304', 'district_id' => '94', 'tehsil' => 'Bahawalpur City'],
            ['id' => '305', 'district_id' => '94', 'tehsil' => 'Bahawalpur Saddar'],
            ['id' => '306', 'district_id' => '94', 'tehsil' => 'Hasilpur'],
            ['id' => '307', 'district_id' => '94', 'tehsil' => 'Khairpur Tamewali'],
            ['id' => '308', 'district_id' => '94', 'tehsil' => 'Yazman'],
            ['id' => '309', 'district_id' => '95', 'tehsil' => 'Bhakkar'],
            ['id' => '310', 'district_id' => '95', 'tehsil' => 'Darya Khan'],
            ['id' => '311', 'district_id' => '95', 'tehsil' => 'Kalur Kot'],
            ['id' => '312', 'district_id' => '95', 'tehsil' => 'Mankera'],
            ['id' => '313', 'district_id' => '96', 'tehsil' => 'Chakwal'],
            ['id' => '314', 'district_id' => '96', 'tehsil' => 'Choa Saidan Shah'],
            ['id' => '315', 'district_id' => '96', 'tehsil' => 'Kallar Kahar'],
            ['id' => '316', 'district_id' => '96', 'tehsil' => 'Lawa'],
            ['id' => '317', 'district_id' => '96', 'tehsil' => 'Talagang'],
            ['id' => '318', 'district_id' => '97', 'tehsil' => 'Bhawana'],
            ['id' => '319', 'district_id' => '97', 'tehsil' => 'Chiniot'],
            ['id' => '320', 'district_id' => '97', 'tehsil' => 'Lalian'],
            ['id' => '321', 'district_id' => '98', 'tehsil' => 'Dera Ghazi Khan'],
            ['id' => '322', 'district_id' => '98', 'tehsil' => 'Kot Chatta'],
            ['id' => '323', 'district_id' => '98', 'tehsil' => 'Koh-e-Suleman'],
            ['id' => '324', 'district_id' => '98', 'tehsil' => 'Taunsa'],
            ['id' => '325', 'district_id' => '99', 'tehsil' => 'Chak Jhumra'],
            ['id' => '326', 'district_id' => '99', 'tehsil' => 'Faisalabad City'],
            ['id' => '327', 'district_id' => '99', 'tehsil' => 'Faisalabad Sadar'],
            ['id' => '328', 'district_id' => '99', 'tehsil' => 'Jaranwala'],
            ['id' => '329', 'district_id' => '99', 'tehsil' => 'Sammundri'],
            ['id' => '330', 'district_id' => '99', 'tehsil' => 'Tandlian Wala'],
            ['id' => '331', 'district_id' => '100', 'tehsil' => 'Gujranwala City'],
            ['id' => '332', 'district_id' => '100', 'tehsil' => 'Gujranwala Saddar'],
            ['id' => '333', 'district_id' => '100', 'tehsil' => 'Kamoke'],
            ['id' => '334', 'district_id' => '100', 'tehsil' => 'Nowshera Virkan'],
            ['id' => '335', 'district_id' => '100', 'tehsil' => 'Wazirabad'],
            ['id' => '336', 'district_id' => '101', 'tehsil' => 'Gujrat'],
            ['id' => '337', 'district_id' => '101', 'tehsil' => 'Kharian'],
            ['id' => '338', 'district_id' => '101', 'tehsil' => 'Sarai Alamgir'],
            ['id' => '339', 'district_id' => '101', 'tehsil' => 'Jalalpur Jattan'],
            ['id' => '340', 'district_id' => '102', 'tehsil' => 'Hafizabad'],
            ['id' => '341', 'district_id' => '102', 'tehsil' => 'Pindi Bhattian'],
            ['id' => '342', 'district_id' => '103', 'tehsil' => '18-Hazari'],
            ['id' => '343', 'district_id' => '103', 'tehsil' => 'Ahmadpur Sial'],
            ['id' => '344', 'district_id' => '103', 'tehsil' => 'Jhang'],
            ['id' => '345', 'district_id' => '103', 'tehsil' => 'Shorkot'],
            ['id' => '346', 'district_id' => '104', 'tehsil' => 'Dina'],
            ['id' => '347', 'district_id' => '104', 'tehsil' => 'Jhelum'],
            ['id' => '348', 'district_id' => '104', 'tehsil' => 'Pind Dadan Khan'],
            ['id' => '349', 'district_id' => '104', 'tehsil' => 'Sohawa'],
            ['id' => '350', 'district_id' => '105', 'tehsil' => 'Chunian'],
            ['id' => '351', 'district_id' => '105', 'tehsil' => 'Kasur'],
            ['id' => '352', 'district_id' => '105', 'tehsil' => 'Kot Radha Kishan'],
            ['id' => '353', 'district_id' => '105', 'tehsil' => 'Pattoki'],
            ['id' => '354', 'district_id' => '106', 'tehsil' => 'Jahanian'],
            ['id' => '355', 'district_id' => '106', 'tehsil' => 'Kabirwala'],
            ['id' => '356', 'district_id' => '106', 'tehsil' => 'Khanewal'],
            ['id' => '357', 'district_id' => '106', 'tehsil' => 'Mian Channu'],
            ['id' => '358', 'district_id' => '107', 'tehsil' => 'Khushab'],
            ['id' => '359', 'district_id' => '107', 'tehsil' => 'Nurpur Thal'],
            ['id' => '360', 'district_id' => '107', 'tehsil' => 'Quaidabad'],
            ['id' => '361', 'district_id' => '107', 'tehsil' => 'Naushera'],
            ['id' => '362', 'district_id' => '108', 'tehsil' => 'Lahore Cantt'],
            ['id' => '363', 'district_id' => '108', 'tehsil' => 'Lahore City'],
            ['id' => '364', 'district_id' => '108', 'tehsil' => 'Model Town'],
            ['id' => '365', 'district_id' => '108', 'tehsil' => 'Raiwind'],
            ['id' => '366', 'district_id' => '108', 'tehsil' => 'Shalimar'],
            ['id' => '367', 'district_id' => '109', 'tehsil' => 'Chaubara'],
            ['id' => '368', 'district_id' => '109', 'tehsil' => 'Karor Lal Esan'],
            ['id' => '369', 'district_id' => '109', 'tehsil' => 'Layyah'],
            ['id' => '370', 'district_id' => '110', 'tehsil' => 'Dunyapur'],
            ['id' => '371', 'district_id' => '110', 'tehsil' => 'Kahror Pacca'],
            ['id' => '372', 'district_id' => '110', 'tehsil' => 'Lodhran'],
            ['id' => '373', 'district_id' => '111', 'tehsil' => 'Malakwal'],
            ['id' => '374', 'district_id' => '111', 'tehsil' => 'Mandi Bahauddin'],
            ['id' => '375', 'district_id' => '111', 'tehsil' => 'Phalia'],
            ['id' => '376', 'district_id' => '112', 'tehsil' => 'Isa Khel'],
            ['id' => '377', 'district_id' => '112', 'tehsil' => 'Mianwali'],
            ['id' => '378', 'district_id' => '112', 'tehsil' => 'Piplan'],
            ['id' => '379', 'district_id' => '113', 'tehsil' => 'Jalalpur Pirwala'],
            ['id' => '380', 'district_id' => '113', 'tehsil' => 'Multan City'],
            ['id' => '381', 'district_id' => '113', 'tehsil' => 'Multan Saddar'],
            ['id' => '382', 'district_id' => '113', 'tehsil' => 'Shujabad'],
            ['id' => '383', 'district_id' => '114', 'tehsil' => 'Alipur'],
            ['id' => '384', 'district_id' => '114', 'tehsil' => 'Jatoi'],
            ['id' => '385', 'district_id' => '114', 'tehsil' => 'Kot Addu'],
            ['id' => '386', 'district_id' => '114', 'tehsil' => 'Muzaffargarh'],
            ['id' => '387', 'district_id' => '115', 'tehsil' => 'Narowal'],
            ['id' => '388', 'district_id' => '115', 'tehsil' => 'Shakargarh'],
            ['id' => '389', 'district_id' => '115', 'tehsil' => 'Zafarwal'],
            ['id' => '390', 'district_id' => '116', 'tehsil' => 'Nankana Sahib'],
            ['id' => '391', 'district_id' => '116', 'tehsil' => 'Sangla Hill'],
            ['id' => '392', 'district_id' => '116', 'tehsil' => 'Shah Kot'],
            ['id' => '393', 'district_id' => '117', 'tehsil' => 'Depalpur'],
            ['id' => '394', 'district_id' => '117', 'tehsil' => 'Okara'],
            ['id' => '395', 'district_id' => '117', 'tehsil' => 'Renala Khurd'],
            ['id' => '396', 'district_id' => '118', 'tehsil' => 'Arifwala'],
            ['id' => '397', 'district_id' => '118', 'tehsil' => 'Pakpattan'],
            ['id' => '398', 'district_id' => '119', 'tehsil' => 'Khanpur'],
            ['id' => '399', 'district_id' => '119', 'tehsil' => 'Liaquatpur'],
            ['id' => '400', 'district_id' => '119', 'tehsil' => 'Rahim Yar Khan'],
            ['id' => '401', 'district_id' => '119', 'tehsil' => 'Sadiqabad'],
            ['id' => '402', 'district_id' => '120', 'tehsil' => 'Jampur'],
            ['id' => '403', 'district_id' => '120', 'tehsil' => 'Rajanpur'],
            ['id' => '404', 'district_id' => '120', 'tehsil' => 'Rojhan'],
            ['id' => '405', 'district_id' => '121', 'tehsil' => 'Gujar Khan'],
            ['id' => '406', 'district_id' => '121', 'tehsil' => 'Kahuta'],
            ['id' => '407', 'district_id' => '121', 'tehsil' => 'Kallar Syedan'],
            ['id' => '408', 'district_id' => '121', 'tehsil' => 'Kotli Sattian'],
            ['id' => '409', 'district_id' => '121', 'tehsil' => 'Murree'],
            ['id' => '410', 'district_id' => '121', 'tehsil' => 'Rawalpindi'],
            ['id' => '411', 'district_id' => '121', 'tehsil' => 'Taxila'],
            ['id' => '412', 'district_id' => '122', 'tehsil' => 'Chichawatni'],
            ['id' => '413', 'district_id' => '122', 'tehsil' => 'Sahiwal'],
            ['id' => '414', 'district_id' => '122', 'tehsil' => 'Noor Shah'],
            ['id' => '415', 'district_id' => '123', 'tehsil' => 'Bhalwal'],
            ['id' => '416', 'district_id' => '123', 'tehsil' => 'Bhera'],
            ['id' => '417', 'district_id' => '123', 'tehsil' => 'Kot Momin'],
            ['id' => '418', 'district_id' => '123', 'tehsil' => 'Sahiwal'],
            ['id' => '419', 'district_id' => '123', 'tehsil' => 'Sargodha'],
            ['id' => '420', 'district_id' => '123', 'tehsil' => 'Shahpur'],
            ['id' => '421', 'district_id' => '123', 'tehsil' => 'Sillanwali'],
            ['id' => '422', 'district_id' => '124', 'tehsil' => 'Firozewala'],
            ['id' => '423', 'district_id' => '124', 'tehsil' => 'Muridke'],
            ['id' => '424', 'district_id' => '124', 'tehsil' => 'Safdarabad'],
            ['id' => '425', 'district_id' => '124', 'tehsil' => 'Sharak Pur'],
            ['id' => '426', 'district_id' => '124', 'tehsil' => 'Sheikhupura'],
            ['id' => '427', 'district_id' => '125', 'tehsil' => 'Daska'],
            ['id' => '428', 'district_id' => '125', 'tehsil' => 'Pasrur'],
            ['id' => '429', 'district_id' => '125', 'tehsil' => 'Sambrial'],
            ['id' => '430', 'district_id' => '125', 'tehsil' => 'Sialkot'],
            ['id' => '431', 'district_id' => '126', 'tehsil' => 'Gojra'],
            ['id' => '432', 'district_id' => '126', 'tehsil' => 'Pirmahal'],
            ['id' => '433', 'district_id' => '126', 'tehsil' => 'Toba Tek Singh'],
            ['id' => '434', 'district_id' => '127', 'tehsil' => 'Burewala'],
            ['id' => '435', 'district_id' => '127', 'tehsil' => 'Mailsi'],
            ['id' => '436', 'district_id' => '127', 'tehsil' => 'Vehari'],
            ['id' => '437', 'district_id' => '128', 'tehsil' => 'Badin'],
            ['id' => '438', 'district_id' => '128', 'tehsil' => 'Nindo Shaher'],
            ['id' => '439', 'district_id' => '128', 'tehsil' => 'Khoski'],
            ['id' => '440', 'district_id' => '128', 'tehsil' => 'Golarchi'],
            ['id' => '441', 'district_id' => '128', 'tehsil' => 'Matli'],
            ['id' => '442', 'district_id' => '128', 'tehsil' => 'Shaheed Fazal Rahu'],
            ['id' => '443', 'district_id' => '128', 'tehsil' => 'Talhar'],
            ['id' => '444', 'district_id' => '128', 'tehsil' => 'ando Bago'],
            ['id' => '445', 'district_id' => '129', 'tehsil' => 'Dadu'],
            ['id' => '446', 'district_id' => '129', 'tehsil' => 'Johi'],
            ['id' => '447', 'district_id' => '129', 'tehsil' => 'Khairpur Nathan Shah'],
            ['id' => '448', 'district_id' => '129', 'tehsil' => 'Mehar'],
            ['id' => '449', 'district_id' => '130', 'tehsil' => 'Daharki'],
            ['id' => '450', 'district_id' => '130', 'tehsil' => 'Ghotki'],
            ['id' => '451', 'district_id' => '130', 'tehsil' => 'Khangarh (Khanpur)'],
            ['id' => '452', 'district_id' => '130', 'tehsil' => 'Mirpur Mathelo'],
            ['id' => '453', 'district_id' => '130', 'tehsil' => 'Ubauro'],
            ['id' => '454', 'district_id' => '131', 'tehsil' => 'Hyderabad City'],
            ['id' => '455', 'district_id' => '131', 'tehsil' => 'Hyderabad Saddar'],
            ['id' => '456', 'district_id' => '131', 'tehsil' => 'Latifabad'],
            ['id' => '457', 'district_id' => '131', 'tehsil' => 'Qasimabad'],
            ['id' => '458', 'district_id' => '132', 'tehsil' => 'Garhi Khairo'],
            ['id' => '459', 'district_id' => '132', 'tehsil' => 'Jacobabad'],
            ['id' => '460', 'district_id' => '132', 'tehsil' => 'Thul'],
            ['id' => '461', 'district_id' => '133', 'tehsil' => 'Jamshoro'],
            ['id' => '462', 'district_id' => '133', 'tehsil' => 'Sehwan'],
            ['id' => '463', 'district_id' => '133', 'tehsil' => 'Kotri'],
            ['id' => '464', 'district_id' => '133', 'tehsil' => 'Manjhand'],
            ['id' => '465', 'district_id' => '133', 'tehsil' => 'Thano Bula Khan'],
            ['id' => '466', 'district_id' => '134', 'tehsil' => 'Gulberg Town'],
            ['id' => '467', 'district_id' => '134', 'tehsil' => 'Liaquatabad Town'],
            ['id' => '468', 'district_id' => '134', 'tehsil' => 'New Karachi Town'],
            ['id' => '469', 'district_id' => '134', 'tehsil' => 'North Nazimabad Town'],
            ['id' => '470', 'district_id' => '134', 'tehsil' => 'Nazimabad'],
            ['id' => '471', 'district_id' => '135', 'tehsil' => 'Gulshan Town'],
            ['id' => '472', 'district_id' => '135', 'tehsil' => 'Jamshed Town'],
            ['id' => '473', 'district_id' => '135', 'tehsil' => 'Ferozabad'],
            ['id' => '474', 'district_id' => '135', 'tehsil' => 'Gulshan-E-Iqbal'],
            ['id' => '475', 'district_id' => '135', 'tehsil' => 'Gulzar-E-Hijri'],
            ['id' => '476', 'district_id' => '136', 'tehsil' => 'Lyari Town'],
            ['id' => '477', 'district_id' => '136', 'tehsil' => 'Saddar Town'],
            ['id' => '478', 'district_id' => '136', 'tehsil' => 'Aram Bahg'],
            ['id' => '479', 'district_id' => '136', 'tehsil' => 'Civil Line'],
            ['id' => '480', 'district_id' => '136', 'tehsil' => 'Garden'],
            ['id' => '481', 'district_id' => '137', 'tehsil' => 'Baldia Town'],
            ['id' => '482', 'district_id' => '137', 'tehsil' => 'Kemari Town'],
            ['id' => '483', 'district_id' => '137', 'tehsil' => 'S.I.T.E. Town'],
            ['id' => '484', 'district_id' => '137', 'tehsil' => 'Harbour'],
            ['id' => '485', 'district_id' => '137', 'tehsil' => 'Manghopir'],
            ['id' => '486', 'district_id' => '137', 'tehsil' => 'Maripur'],
            ['id' => '487', 'district_id' => '137', 'tehsil' => 'Mominabad'],
            ['id' => '488', 'district_id' => '138', 'tehsil' => 'Kandhkot'],
            ['id' => '489', 'district_id' => '138', 'tehsil' => 'Kashmore'],
            ['id' => '490', 'district_id' => '138', 'tehsil' => 'Tangwani'],
            ['id' => '491', 'district_id' => '139', 'tehsil' => 'Faiz Ganj'],
            ['id' => '492', 'district_id' => '139', 'tehsil' => 'Gambat'],
            ['id' => '493', 'district_id' => '139', 'tehsil' => 'Khairpur Mirs'],
            ['id' => '494', 'district_id' => '139', 'tehsil' => 'Kingri'],
            ['id' => '495', 'district_id' => '139', 'tehsil' => 'Kot Diji'],
            ['id' => '496', 'district_id' => '139', 'tehsil' => 'Nara'],
            ['id' => '497', 'district_id' => '139', 'tehsil' => 'Sobhodero'],
            ['id' => '498', 'district_id' => '139', 'tehsil' => 'Thari Mirwah'],
            ['id' => '499', 'district_id' => '140', 'tehsil' => 'Korangi Town'],
            ['id' => '500', 'district_id' => '140', 'tehsil' => 'Landhi Town'],
            ['id' => '501', 'district_id' => '140', 'tehsil' => 'Shah Faisal Town'],
            ['id' => '502', 'district_id' => '140', 'tehsil' => 'Model Colony'],
            ['id' => '503', 'district_id' => '141', 'tehsil' => 'Bakrani'],
            ['id' => '504', 'district_id' => '141', 'tehsil' => 'Dokri'],
            ['id' => '505', 'district_id' => '141', 'tehsil' => 'Larkana'],
            ['id' => '506', 'district_id' => '141', 'tehsil' => 'Rato Dero'],
            ['id' => '507', 'district_id' => '142', 'tehsil' => 'Bin Qasim Town'],
            ['id' => '508', 'district_id' => '142', 'tehsil' => 'Gadap Town'],
            ['id' => '509', 'district_id' => '142', 'tehsil' => 'Malir Town'],
            ['id' => '510', 'district_id' => '142', 'tehsil' => 'Jinnah'],
            ['id' => '511', 'district_id' => '142', 'tehsil' => 'Ibrahim Hyderi'],
            ['id' => '512', 'district_id' => '142', 'tehsil' => 'urad Memon'],
            ['id' => '513', 'district_id' => '142', 'tehsil' => 'Shah Murad'],
            ['id' => '514', 'district_id' => '143', 'tehsil' => 'Hala'],
            ['id' => '515', 'district_id' => '143', 'tehsil' => 'Matiari'],
            ['id' => '516', 'district_id' => '143', 'tehsil' => 'Saeedabad'],
            ['id' => '517', 'district_id' => '144', 'tehsil' => 'Digri'],
            ['id' => '518', 'district_id' => '144', 'tehsil' => 'Goth Allah bachayo wassan'],
            ['id' => '519', 'district_id' => '144', 'tehsil' => 'Jhuddo'],
            ['id' => '520', 'district_id' => '144', 'tehsil' => 'Kot Ghulam Mohammad'],
            ['id' => '521', 'district_id' => '144', 'tehsil' => 'Mirpur Khas'],
            ['id' => '522', 'district_id' => '144', 'tehsil' => 'Shujabad'],
            ['id' => '523', 'district_id' => '144', 'tehsil' => 'Sindhri'],
            ['id' => '524', 'district_id' => '145', 'tehsil' => 'Bhiria'],
            ['id' => '525', 'district_id' => '145', 'tehsil' => 'Kandioro'],
            ['id' => '526', 'district_id' => '145', 'tehsil' => 'Mehrabpur'],
            ['id' => '527', 'district_id' => '145', 'tehsil' => 'Moro'],
            ['id' => '528', 'district_id' => '145', 'tehsil' => 'Naushahro Feroze'],
            ['id' => '529', 'district_id' => '146', 'tehsil' => 'Miro Khan'],
            ['id' => '530', 'district_id' => '146', 'tehsil' => 'Nasirabad'],
            ['id' => '531', 'district_id' => '146', 'tehsil' => 'Kambar'],
            ['id' => '532', 'district_id' => '146', 'tehsil' => 'Qubo Saeed Khan'],
            ['id' => '533', 'district_id' => '146', 'tehsil' => 'Shahdadkot'],
            ['id' => '534', 'district_id' => '146', 'tehsil' => 'Sijawal Junejo'],
            ['id' => '535', 'district_id' => '146', 'tehsil' => 'Warah'],
            ['id' => '536', 'district_id' => '147', 'tehsil' => 'Jam Nawaz Ali'],
            ['id' => '537', 'district_id' => '147', 'tehsil' => 'Khipro'],
            ['id' => '538', 'district_id' => '147', 'tehsil' => 'Sanghar'],
            ['id' => '539', 'district_id' => '147', 'tehsil' => 'Shahdadpur'],
            ['id' => '540', 'district_id' => '147', 'tehsil' => 'Sinjhoro'],
            ['id' => '541', 'district_id' => '147', 'tehsil' => 'Tando Adam'],
            ['id' => '542', 'district_id' => '148', 'tehsil' => 'Daulatpur (Qazi Ahmed)'],
            ['id' => '543', 'district_id' => '148', 'tehsil' => 'Daur'],
            ['id' => '544', 'district_id' => '148', 'tehsil' => 'Nawabshah'],
            ['id' => '545', 'district_id' => '148', 'tehsil' => 'Sakrand'],
            ['id' => '546', 'district_id' => '149', 'tehsil' => 'Garhi Yasin'],
            ['id' => '547', 'district_id' => '149', 'tehsil' => 'Khanpur'],
            ['id' => '548', 'district_id' => '149', 'tehsil' => 'Lakhi'],
            ['id' => '549', 'district_id' => '149', 'tehsil' => 'Shikarpur'],
            ['id' => '550', 'district_id' => '150', 'tehsil' => 'Jati'],
            ['id' => '551', 'district_id' => '150', 'tehsil' => 'Kharo Chan'],
            ['id' => '552', 'district_id' => '150', 'tehsil' => 'Mirpur Bathoro'],
            ['id' => '553', 'district_id' => '150', 'tehsil' => 'Shah Bunder'],
            ['id' => '554', 'district_id' => '150', 'tehsil' => 'Sujawal'],
            ['id' => '555', 'district_id' => '151', 'tehsil' => 'New Sukkur'],
            ['id' => '556', 'district_id' => '151', 'tehsil' => 'Pano Aqil'],
            ['id' => '557', 'district_id' => '151', 'tehsil' => 'Rohri'],
            ['id' => '558', 'district_id' => '151', 'tehsil' => 'Salehpat'],
            ['id' => '559', 'district_id' => '151', 'tehsil' => 'Sukkur'],
            ['id' => '560', 'district_id' => '152', 'tehsil' => 'Chamber'],
            ['id' => '561', 'district_id' => '152', 'tehsil' => 'Jhando Mari'],
            ['id' => '562', 'district_id' => '152', 'tehsil' => 'Nasarpur'],
            ['id' => '563', 'district_id' => '152', 'tehsil' => 'Tando Allahyar'],
            ['id' => '564', 'district_id' => '153', 'tehsil' => 'Bulri Shah Karim'],
            ['id' => '565', 'district_id' => '153', 'tehsil' => 'Tando Ghulam Hyder'],
            ['id' => '566', 'district_id' => '153', 'tehsil' => 'Tando Muhammad Khan'],
            ['id' => '567', 'district_id' => '154', 'tehsil' => 'Chachro'],
            ['id' => '568', 'district_id' => '154', 'tehsil' => 'Dhali'],
            ['id' => '569', 'district_id' => '154', 'tehsil' => 'Diplo'],
            ['id' => '570', 'district_id' => '154', 'tehsil' => 'Kaloi'],
            ['id' => '571', 'district_id' => '154', 'tehsil' => 'Islamkot'],
            ['id' => '572', 'district_id' => '154', 'tehsil' => 'Mithi'],
            ['id' => '573', 'district_id' => '154', 'tehsil' => 'Nagarparkar'],
            ['id' => '574', 'district_id' => '155', 'tehsil' => 'Ghorabari'],
            ['id' => '575', 'district_id' => '155', 'tehsil' => 'Keti Bunder'],
            ['id' => '576', 'district_id' => '155', 'tehsil' => 'irpur Sakro'],
            ['id' => '577', 'district_id' => '155', 'tehsil' => 'Thatta'],
            ['id' => '578', 'district_id' => '156', 'tehsil' => 'Kunri'],
            ['id' => '579', 'district_id' => '156', 'tehsil' => 'Pithoro'],
            ['id' => '580', 'district_id' => '156', 'tehsil' => 'Samaro'],
            ['id' => '581', 'district_id' => '156', 'tehsil' => 'Umerkot'],
        ];
    }
}
